<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Akka.TestKit.Xunit2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\plugins\App.Ecs\App.Ecs.csproj" />
    <ProjectReference Include="..\..\contracts\App.Ecs\App.Ecs.csproj" />
  </ItemGroup>
</Project>
