<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);GeneratedOut\**;**\GeneratedOut\**</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup>
    <UseProjectReferences Condition="'$(UseProjectReferences)' == ''">false</UseProjectReferences>
    <PlateProjectsRoot Condition="'$(PlateProjectsRoot)' == ''">/Users/apprenticegc/Work/lunar-horse/plate-projects</PlateProjectsRoot>
    <YokanProjectsRoot Condition="'$(YokanProjectsRoot)' == ''">/Users/apprenticegc/Work/lunar-horse/yokan-projects</YokanProjectsRoot>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' != 'Cross.Abstractions'">
    <Compile Include="$(MSBuildThisFileDirectory)project\contracts\Cross.Abstractions\Polyfills\IsExternalInit.cs"
             Link="Polyfills\IsExternalInit.cs" />
  </ItemGroup>

</Project>
