<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>FantaSim.App.Remote</RootNamespace>
    <AssemblyName>FantaSim.App.Remote</AssemblyName>
    <ServiceArchiTier>T3</ServiceArchiTier>
  </PropertyGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="ServiceArchiTier" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\contracts\App.Command\App.Command.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GiantCroissant.ServiceArchi.Contracts" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
