<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>FantaSim.App.Common</RootNamespace>
    <AssemblyName>FantaSim.App.Common</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GiantCroissant.ServiceArchi.Contracts" />
    <PackageReference Include="GiantCroissant.ServiceArchi.Core" />
    <PackageReference Include="GiantCroissant.PluginArchi.Extensibility.Abstractions" />
    <PackageReference Include="GiantCroissant.PluginArchi.Extensibility.Hosting" />
    <PackageReference Include="GiantCroissant.DependencyArchi.Abstractions" />
    <PackageReference Include="GiantCroissant.DependencyArchi.MicrosoftExtensions" />
    <PackageReference Include="GiantCroissant.DependencyArchi.SourceGenerators" PrivateAssets="all" />
    <PackageReference Include="GiantCroissant.CrosscutFoundation.Messaging.Contracts" />
    <PackageReference Include="GiantCroissant.CrosscutFoundation.Messaging.MessagePipe" />
    <PackageReference Include="GiantCroissant.CrosscutFoundation.Messaging.MessagePipe.ServiceArchi" />
    <PackageReference Include="GiantCroissant.CrosscutFoundation.Logging.Contracts" />
    <PackageReference Include="GiantCroissant.CrosscutFoundation.Logging.Core" />
    <PackageReference Include="GiantCroissant.CrosscutFoundation.Logging.Console" />
    <PackageReference Include="GiantCroissant.CrosscutFoundation.Logging.Console.ServiceArchi" />
    <PackageReference Include="GiantCroissant.CrosscutFoundation.Logging.ServiceArchi" />
    <PackageReference Include="GiantCroissant.RegistryArchi.Core" />
    <PackageReference Include="GiantCroissant.RegistryArchi.Contracts" />
    <PackageReference Include="Akka" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
