<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>App.ExternalTools.CodeGen</RootNamespace>
    <AssemblyName>App.ExternalTools.CodeGen</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
