<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />

  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\plugins\App.Ui\App.Ui.csproj" />
    <ProjectReference Include="..\..\plugins\App.Ui.Activity\App.Ui.Activity.csproj" />
    <ProjectReference Include="..\..\plugins\App.Ui.NodeGraph\App.Ui.NodeGraph.csproj" />
    <ProjectReference Include="..\..\plugins\App.NodeGraph\App.NodeGraph.csproj" />
    <ProjectReference Include="..\..\contracts\App.Ui\App.Ui.csproj" />
    <ProjectReference Include="..\..\contracts\App.Command\App.Command.csproj" />
    <ProjectReference Include="..\..\contracts\App.NodeGraph\App.NodeGraph.csproj" />
    <ProjectReference Include="..\..\plugins\App.World\App.World.csproj" />
    <ProjectReference Include="..\..\contracts\App.World\App.World.csproj" />
  </ItemGroup>
</Project>
