<Project Sdk="Godot.NET.Sdk/4.6.3">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>CompleteApp</RootNamespace>
    <Nullable>enable</Nullable>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\plugins\App.Common\App.Common.csproj" />
    <ProjectReference Include="..\..\plugins\App.Resource\App.Resource.csproj" />
    <ProjectReference Include="..\..\plugins\App.Resource.Bundle.Seam\App.Resource.Bundle.Seam.csproj" />
    <ProjectReference Include="..\..\plugins\App.SceneFlow\App.SceneFlow.csproj" />
    <ProjectReference Include="..\..\plugins\App.Ecs\App.Ecs.csproj" />
    <ProjectReference Include="..\..\plugins\App.World\App.World.csproj" />
    <ProjectReference Include="..\..\plugins\App.Command\App.Command.csproj" />
    <ProjectReference Include="..\..\plugins\App.World.Projection\App.World.Projection.csproj" />
    <ProjectReference Include="..\..\plugins\App.Ui\App.Ui.csproj" />
    <ProjectReference Include="..\..\plugins\App.Ui.Seam\App.Ui.Seam.csproj" />
    <ProjectReference Include="..\..\plugins\App.NodeGraph\App.NodeGraph.csproj" />
    <ProjectReference Include="..\..\plugins\App.Ui.NodeGraph\App.Ui.NodeGraph.csproj" />
    <ProjectReference Include="..\..\plugins\App.Iii\App.Iii.csproj" />
    <ProjectReference Include="..\..\plugins\App.Iii.Seam\App.Iii.Seam.csproj" />
  </ItemGroup>
</Project>
